version: '3'
services:
  mysql:
    image: mysql:5.7.37
    restart: always
    container_name: teletraan-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '56tP3!U8NEa$DYwT'
      MYSQL_DATABASE: teletraan
      MYSQL_USER: teletraan
      MYSQL_PASSWORD: Teletraan-OCR@1024
    ports:
      - 3307:3306
    networks:
      - ocr
    volumes:
      - your_customer_mysql_dir:/var/lib/mysql
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
  muggle-ocr:
    image: registry.cn-hangzhou.aliyuncs.com/private_app/teletraan-ocr-project:1.0.3
    restart: always
    container_name: teletraan-muggle-ocr
    environment:
      FLASK_ENV: development
      LANG: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
      APP_TIMEZONE: UTC
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: teletraan
      DATABASE_NAME: teletraan
      DATABASE_PASSWORD: Teletraan-OCR@1024
    ports:
      - 5000:5000
    networks:
      - ocr
    depends_on:
      - mysql

networks:
  ocr: {}
