"""empty message

Revision ID: 50201fad7a29
Revises: 
Create Date: 2022-04-24 10:51:55.014002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50201fad7a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_logging',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=64), nullable=True),
    sa.Column('image_file_name', sa.String(length=256), nullable=True),
    sa.Column('ocr_result', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ocr_logging_seq'), 'ocr_logging', ['seq'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_logging_seq'), table_name='ocr_logging')
    op.drop_table('ocr_logging')
    # ### end Alembic commands ###
